#define createIntToken(x) createIntToken(nowhere, x)
#define createFloatToken(x) createFloatToken(nowhere, x)
#define createIdentifierToken(x) createIdentifierToken(nowhere, x)
#define createTupleToken(x) createTupleToken(nowhere, x)
#define createCallToken(x) createCallToken(nowhere, x)
#define createBinaryOpToken(op, left, right) createBinaryOpToken(nowhere, op, left, right)
#define createUnaryOpToken(x, y) createUnaryOpToken(nowhere, x, y)
#define createAssignmentToken(x, y) createAssignmentToken(nowhere, x, y)
#define createBlockToken(x) createBlockToken(nowhere, x)
#define createIfToken(x, y) createIfToken(nowhere, x, y)
#define createWhileToken(x, y) createWhileToken(nowhere, x, y)
#define createFuncToken(x, y, z) createFuncToken(nowhere, x, y, z)
#define createReturnToken(x) createReturnToken(nowhere, x)
#define createCondJumpToken(x, y, z) createCondJumpToken(nowhere, x, y, z)
